driver:
  name: vagrant

provisioner:
  name: chef_zero
  test_repo_uri: https://github.com/dev-sec/tests-nginx-hardening.git

verifier:
  name: inspec
  sudo: true

platforms:
- name: ubuntu-12.04
- name: ubuntu-14.04
- name: ubuntu-16.04
- name: centos-6.8
- name: centos-7.2
- name: oracle-6.4
  driver_config:
    box: oracle-6.4
    box_url: https://storage.us2.oraclecloud.com/v1/istoilis-istoilis/vagrant/oel64-64.box
- name: oracle-6.5
  driver_config:
    box: oracle-6.5
    box_url: https://storage.us2.oraclecloud.com/v1/istoilis-istoilis/vagrant/oel65-64.box
- name: debian-7.11
- name: debian-8.5

suites:
- name: default
  run_list:
  - recipe[apt]
  - recipe[nginx-hardening::upgrades]
  - recipe[nginx]
  - recipe[nginx-hardening]
  verifier:
    inspec_tests:
      - https://github.com/dev-sec/tests-nginx-hardening
